# Generated by Django 3.2.5 on 2021-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pora', '0002_alter_website_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
