# Generated by Django 3.2.5 on 2021-08-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pora', '0003_alter_website_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website',
            new_name='Codigo',
        ),
    ]
