# Generated by Django 3.2.5 on 2021-08-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pora', '0004_rename_website_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigo',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='static/qr_codes'),
        ),
    ]
