# Generated by Django 3.2.5 on 2021-08-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pora', '0006_alter_codigo_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=300)),
                ('cargo', models.CharField(max_length=300)),
                ('venta', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Codigo',
            new_name='Codigo_qr',
        ),
    ]
