# Generated by Django 3.2.5 on 2021-08-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pora', '0007_auto_20210811_0031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codigo_qr',
            new_name='Codigo',
        ),
    ]
